### ISSUE TITLE
1297 런타임 에러

### ISSUE THREAD

**Issue by songbyungsub** [AIVLE-School-2-Study/Algorithm-study#20]
```python
import sys
import math

a,b,c = map(int,sys.stdin.readlines())
garo = a*c /math.sqrt(a**2 + b**2)
sero = a*b /math.sqrt(a**2 + b**2)
print(math.trunc(sero), math.trunc(garo))
```

어느 부분에서 런타임 오류가 나는건지 조언좀 부탁드립니다! ㅜㅜ

**Comment by HeekunLim** [comment]
입력이 문제인거 같아요
입력을 a, b, c = map(int,sys.stdin.readline().split())
으로 바꿔보세요!

확실하지는 않은데 제 예상으로는
readline()은 파일에서 한 줄만 입력 받는거고
readlines()는 파일에서 모든 줄을 입력 받는거라 계속 입력해도 종료 되지 않는거 같아요!

split()은 입력 여러개일 때 나눠주는 역할이라 넣었어요!

**Comment by songbyungsub** [comment]
말씀해주신 부분 수정해보니 잘 되네요 감사합니다!! 그리고 계산식도 틀렸었네용 ㅋㅋㅋㅋ
